const ImagePath = {
  addicon: require('../assests/images/iconadd.png'),
  backicon: require('../assests/images/back_icon.png'),
  spotifyicon: require('../assests/images/SpotifyIcon.png'),
  albumsPic: require('../assests/images/Albums.png'),
  Splash : require('../assests/images/Splash.png'),
  applogo: require('../assests/images/logo.png'),
  copyright: require('../assests/images/Copyright.png'),
  applemusic: require('../assests/images/itunesicon.png'),
  homeactive: require('../assests/images/icon-home-active.png'),
  homeinactive: require('../assests/images/icon-home.png'),
  sendiconcopy:require('../assests/images/icon-send-copy.png'),
  homelightbg:require('../assests/images/Rectangle.png'),
  iconbox:require('../assests/images/icon-box.png'),
  searchactive: require('./images/icon-search-active.png'),
  searchinactive: require('./images/icon-search.png'),
  addbtn: require('./images/Button-Add.png'),
  notificationactive: require('./images/icon-active.png'),
  notificationinactive: require('./images/icon-inactive.png'),
  boxactive: require('./images/icon-box-active.png'),
  boxinactive: require('./images/icon-box.png'),
  dp: require('../assests/images/dp.png'),
  dp1: require('../assests/images/Mask.png'),
  dp2: require('../assests/images/Group1.png'),
  iconmenu: require('../assests/images/icon-menu.png'),
  settings: require('./images/settings.png'),
  profiletrack1: require('./images/profiletrack1.png'),
  profiletrack2: require('./images/profiletrack2.png'),
  profiletrack3: require('./images/profiletrack3.png'),
  profiletrack4: require('./images/profiletrack4.png'),
  profiletrack5: require('./images/profiletrack5.png'),
  profiletrack6: require('./images/profiletrack.png'),
  gradientbar: require('./images/rectanglegradien.png'),
  change: require('./images/change.png'),
  play: require('./images/play.png'),
  searchicon: require('./images/icons-search-black.png'),
  threedots: require('./images/moredots.png'),
  unsaved: require('./images/whiteunsave.png'),
  inbox: require('./images/inbox.png'),
  noposts: require('./images/NoPosts.png'),
  facebook: require('./images/facebook.png'),
  newmessage: require('./images/Iconnewmessage.png')

};

export default ImagePath;

