default_platform(:ios)

platform :ios do
  desc "Build and upload a beta to TestFlight"
  lane :beta do
    # optionally fetch and install certificates/provisioning with match
    if ENV['MATCH_GIT_URL'] && ENV['MATCH_GIT_URL'] != ''
      match(
        type: "appstore",
        readonly: ENV['MATCH_READONLY'] == 'true' ? true : false,
        git_url: ENV['MATCH_GIT_URL'],
        git_branch: ENV['MATCH_GIT_BRANCH'] || nil,
        verbose: false
      )
    end

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_KEY_PATH'],
      in_house: false
    )

    build_app(
      workspace: "ios/Choona.xcworkspace",
      scheme: ENV['SCHEME'] || "Choona",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key)
  end
end
