
export const ASYNC_STORAGE_REQUEST = "ASYNC_STORAGE_REQUEST";
export const ASYNC_STORAGE_SUCCESS = "ASYNC_STORAGE_SUCCESS";
export const ASYNC_STORAGE_FAILURE = "ASYNC_STORAGE_FAILURE";

export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";
