
export const ASYNC_STORAGE_REQUEST = "ASYNC_STORAGE_REQUEST";
export const ASYNC_STORAGE_SUCCESS = "ASYNC_STORAGE_SUCCESS";
export const ASYNC_STORAGE_FAILURE = "ASYNC_STORAGE_FAILURE";

export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAILURE = "USER_SEARCH_FAILURE";

export const USER_FOLLOW_UNFOLLOW_REQUEST = "USER_FOLLOW_UNFOLLOW_REQUEST";
export const USER_FOLLOW_UNFOLLOW_SUCCESS = "USER_FOLLOW_UNFOLLOW_SUCCESS";
export const USER_FOLLOW_UNFOLLOW_FAILURE = "USER_FOLLOW_UNFOLLOW_FAILURE";